# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Library

# Model Form Field configuration
form: $/learnkit/h5p/models/library/fields.yaml

# Model Class name
modelClass: LearnKit\H5p\Models\Library

# Default redirect location
defaultRedirect: learnkit/h5p/libraries

# Create page
create:
    title: Create Library
    redirect: learnkit/h5p/libraries/update/:id
    redirectClose: learnkit/h5p/libraries

# Update page
update:
    title: Edit Library
    redirect: learnkit/h5p/libraries
    redirectClose: learnkit/h5p/libraries

# Preview page
preview:
    title: Preview Library
