# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Content

# Model Form Field configuration
form: $/learnkit/h5p/models/content/fields.yaml

# Model Class name
modelClass: LearnKit\H5p\Models\Content

# Default redirect location
defaultRedirect: learnkit/h5p/contents

# Create page
create:
    title: Create Content
    redirect: learnkit/h5p/contents/update/:id
    redirectClose: learnkit/h5p/contents

# Update page
update:
    title: Edit Content
    redirect: learnkit/h5p/contents
    redirectClose: learnkit/h5p/contents

# Preview page
preview:
    title: Preview Content
